FROM node:20-slim as builder

WORKDIR /app

COPY package*.json /app/

RUN npm ci

COPY ./ /app/

CMD [ "npm", "run", "dev", "--host" ]

# FROM nginx:1.23.1

# RUN rm /etc/nginx/conf.d/*

# RUN rm -rf /usr/share/nginx/html/*

# COPY --from=builder /app/dist/ /usr/share/nginx/html
# COPY ./nginx.conf /etc/nginx/conf.d